spring.application.name=pagin-board

# H2 콘솔 활성화
spring.h2.console.enabled=true
# 접속 주소 설정 (기본값은 /h2-console)
spring.h2.console.path=/h2-console

# DB 접속 URL (중요: 이 주소를 메모해두세요)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa